url: https://ai-linkup.github.io
baseurl: /

# Site settings
title: AI-LinkUp 2024
email: mcd@unison.mx
description: "Página web del evento AI-LinkUp de la Universidad de Sonora."


# Team names, titles and social links
people:
- name: Olivia Gutú
  position: Lider
  #social:
  #  - title: linkedin
  #    url: #
- name: Eduardo Acuña
  position: Pláticas, taller, concurso
- name: Adrián Vazquez
  position: Concurso
- name: Julio Waissman
  position: Pláticas y mesa de diálogo


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://x.com/McdUnison
  - title: linkedin
    url: https://linkedin.com/company/mcd-unison
  - title: github
    url: http://github.com/mcd-unison
  - title: medium
    url: https://medium.com/mcd-unison
  

# Postal address (add as many lines as necessary)
address:
  - line: Blvd. Luis Encinas y Rosales s/n Col. Centro. Edificio 3K1 planta baja
  - line: C.P. 83000, Hermosillo, Sonora, México

# Build settings
markdown: kramdown
permalink: pretty
